{{- define "http.config" -}}
[kafka]
input_topic   = "rpc.http"
config_topic  = "crm.config"
output_topic  = "rpc.responses"
group_id      = "{{.Values.kafka.group_prefix}}-http-requester"
brokers       = "{{.Values.kafka.endpoint}}"
{{- end -}}
