{
 "title": "Memcached",
 "description": "Monitors Kubernetes Memcached Pods. Shows memory usage, hit rate, evicts and reclaims rate, items in cache, network stats, commands rate. Requires Memcached Exporter for Prometheus.",
 "tags": [
  "prometheus",
  "memcached"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": "label_values(memcached_up, kubernetes_pod_name)"
   },
   {
    "name": "namespace",
    "query": "label_values(memcached_up, kubernetes_namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(memcached_current_bytes{kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}) / sum(memcached_limit_bytes{kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Hit rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (irate (memcached_commands_total{status=\"hit\",command=\"get\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}[5m])) / sum (irate (memcached_commands_total{command=\"get\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}[5m]\n))",
     "legendFormat": "Hit"
    }
   ]
  },
  {
   "title": "Evicts & Reclaims rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (irate (memcached_items_evicted_total{kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "evicts"
    },
    {
     "expr": "sum (irate (memcached_items_reclaimed_total{kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "reclaims"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (memcached_current_bytes{kubernetes_pod_name=~\"$pod\", kubernetes_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (memcached_limit_bytes{kubernetes_pod_name=~\"$pod\", kubernetes_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Hit & Miss ratio",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_commands_total{status=\"hit\",command=\"get\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}) / sum (memcached_commands_total{command=\"get\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"})",
     "legendFormat": "hit"
    },
    {
     "expr": "sum (memcached_commands_total{status=\"miss\",command=\"get\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}) / sum (memcached_commands_total{command=\"get\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"})",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Evicts (total)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (memcached_items_evicted_total{kubernetes_pod_name=~\"$pod\", kubernetes_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Reclaims (total)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (memcached_items_reclaimed_total{kubernetes_pod_name=~\"$pod\", kubernetes_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Items in cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_current_items{kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (irate (memcached_read_bytes_total{kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum (irate (memcached_written_bytes_total{kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "written"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_current_connections{kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Get & Set ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_commands_total{command=\"get\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}) / (sum (memcached_commands_total{command=\"get\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}) + sum (memcached_commands_total{command=\"set\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}))",
     "legendFormat": "Get"
    },
    {
     "expr": "sum (memcached_commands_total{command=\"set\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"})  / (sum (memcached_commands_total{command=\"get\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}) + sum (memcached_commands_total{command=\"set\",kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}))",
     "legendFormat": "Set"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (irate (memcached_commands_total{kubernetes_pod_name=~\"$pod\",kubernetes_namespace=~\"$namespace\"}[5m])) by (command)",
     "legendFormat": "{{command}}"
    }
   ]
  }
 ]
}