{
 "title": "Notifications",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "system", "label": "system", "query": "http,apns2,fcm,web-push" }
  ]
 },
 "panels": [
  {
   "title": "CPU%",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"staging-$system.*$\"}[1m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\".*\"}) * 100"
    }
   ]
  },
  {
   "title": "RSS%",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod_name=~\"staging-$system.*$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\".*\"}) * 100"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"staging-$system.*$\"}[1m])) by (io_kubernetes_pod_name)",
     "legendFormat": "RX"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"staging-$system.*$\"}[1m])) by (io_kubernetes_pod_name)",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "RSS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",pod_name=~\"staging-$system.*$\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",pod_name=~\"staging-$system.*$\"}[1m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(push_notifications_total{release=\"staging-$system\"}[1m])) by (status)",
     "legendFormat": "status | {{status}}"
    }
   ]
  },
  {
   "title": "Response times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_latency_seconds_bucket{release=\"staging-$system\"}[30s])) by (release, le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_request_latency_seconds_bucket{release=\"staging-$system\"}[30s])) by (release, le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_latency_seconds_bucket{release=\"staging-$system\"}[30s])) by (release, le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_latency_seconds_bucket{release=\"staging-$system\"}[30s])) by (release, le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Kafka lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"staging-http-requester\"}) by (consumergroup, topic) ",
     "legendFormat": "{{consumergroup}}"
    },
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"staging-apns2\"}) by (consumergroup, topic) ",
     "legendFormat": "{{consumergroup}}"
    },
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"staging-fcm\"}) by (consumergroup, topic) ",
     "legendFormat": "{{consumergroup}}"
    },
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"staging-web_push\"}) by (consumergroup, topic) ",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  }
 ]
}