apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "re.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "re.fullname" . }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: {{ template "re.name" . }}
    release: {{ .Release.Name }}
  type: ClusterIP
