kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: {{ template "scylla.fullname" . }}-ssd
provisioner: {{ .Values.storage.provisioner }}
parameters:
{{ toYaml .Values.storage.parameters | indent 2 }}
